name: Auto Create Issues Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Debug - Workflow started
        run: echo "🟢 Workflow triggered successfully!"

      - name: Generate Issue Using Gemini 1.5 Flash
        id: generate
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$GEMINI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "contents": [{
              "parts": [{
                "text": "Generate a GitHub issue about a common React problem developers face, with title and markdown-formatted body."
              }]
            }]
          }' > response.json

      - name: Extract Title and Body from Gemini Response
        id: parse
        run: |
          CONTENT=$(jq -r '.candidates[0].content.parts[0].text' response.json)
          echo "$CONTENT" > full.md
          head -n 1 full.md | sed 's/^# //' > title.txt
          tail -n +2 full.md > issue-body.md

      - name: Debug - Show extracted content
        run: |
          echo "TITLE:"
          cat title.txt
          echo "BODY:"
          cat issue-body.md

      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: ${{ steps.parse.outputs.title }}
          content-filepath: issue-body.md
          labels: react, ai-generated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
