name: 📁 Generate Error Documentation from Issues

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  generate-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub Actions as user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Detect topic from title and body
        id: topic
        run: |
          CONTENT="$(echo '${{ github.event.issue.title }} ${{ github.event.issue.body }}' | tr '[:upper:]' '[:lower:]')"

          if echo "$CONTENT" | grep -q "react"; then
            echo "topic=react" >> $GITHUB_OUTPUT
          elif echo "$CONTENT" | grep -q "javascript"; then
            echo "topic=javascript" >> $GITHUB_OUTPUT
          elif echo "$CONTENT" | grep -q "css"; then
            echo "topic=css" >> $GITHUB_OUTPUT
          elif echo "$CONTENT" | grep -q "jquery"; then
            echo "topic=jquery" >> $GITHUB_OUTPUT
          else
            echo "topic=general" >> $GITHUB_OUTPUT
          fi

      - name: Sanitize folder name from issue title
        id: folder
        run: |
          FOLDER=$(echo "${{ github.event.issue.title }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
          echo "folder=$FOLDER" >> $GITHUB_OUTPUT

      - name: Create README.md from issue
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          FOLDER: ${{ steps.folder.outputs.folder }}
          TOPIC: ${{ steps.topic.outputs.topic }}
        run: |
          mkdir -p "errors/$TOPIC/$FOLDER"
          {
            echo "# 🐞 $ISSUE_TITLE"
            echo
            printf "%s\n" "$ISSUE_BODY"
          } > "errors/$TOPIC/$FOLDER/README.md"

      - name: Commit and push
        run: |
          git add .
          TITLE="${{ github.event.issue.title }}"
          git commit -m "📚 Add error doc: $TITLE" || echo "Nothing to commit"
          git push
