name: 📁 Generate Error Documentation from Issues

on:
  workflow_run:
    workflows: ["Auto Create Issues Every 10 Minutes"]
    types:
      - completed

permissions:
  contents: write
  issues: read

jobs:
  generate-doc:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download issue content
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue list --limit 1 --state open --json number,title,body \
          > latest-issue.json

          TITLE=$(jq -r '.[0].title' latest-issue.json)
          BODY=$(jq -r '.[0].body' latest-issue.json)
          echo "$TITLE" > title.txt
          echo "$BODY" > body.txt

      - name: Detect topic from title and body
        id: topic
        run: |
          CONTENT=$(cat title.txt body.txt | tr '[:upper:]' '[:lower:]')

          if echo "$CONTENT" | grep -q "react"; then
            echo "topic=react" >> $GITHUB_OUTPUT
          elif echo "$CONTENT" | grep -q "javascript"; then
            echo "topic=javascript" >> $GITHUB_OUTPUT
          elif echo "$CONTENT" | grep -q "css"; then
            echo "topic=css" >> $GITHUB_OUTPUT
          elif echo "$CONTENT" | grep -q "jquery"; then
            echo "topic=jquery" >> $GITHUB_OUTPUT
          else
            echo "topic=general" >> $GITHUB_OUTPUT
          fi

      - name: Sanitize folder name from issue title
        id: folder
        run: |
          FOLDER=$(cat title.txt | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
          echo "folder=$FOLDER" >> $GITHUB_OUTPUT

      - name: Create README.md from issue
        run: |
          mkdir -p "errors/${{ steps.topic.outputs.topic }}/${{ steps.folder.outputs.folder }}"
          echo "# 🐞 $(cat title.txt)" > "errors/${{ steps.topic.outputs.topic }}/${{ steps.folder.outputs.folder }}/README.md"
          echo "" >> "errors/${{ steps.topic.outputs.topic }}/${{ steps.folder.outputs.folder }}/README.md"
          cat body.txt >> "errors/${{ steps.topic.outputs.topic }}/${{ steps.folder.outputs.folder }}/README.md"

      - name: Commit and push with PAT
        env:
          TOKEN: ${{ secrets.OPENROCKETS_PAT }}
        run: |
          git add .
          git commit -m "📚 Add error doc from last issue" || echo "Nothing to commit"
          git remote set-url origin https://openrocketsofficial:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD
