name: 📁 Generate Error Documentation from Issues

on:
  issues:
    types: [opened]
permissions:
  contents: write
  
jobs:
  generate-doc:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OPENROCKETS_PAT }}  # Use your PAT stored in repo secrets

      - name: Set up Git user
        run: |
          git config user.name "openrocketsofficial"
          git config user.email "motiontel@outlook.com"  # Use the real email of your alt account

      - name: Detect topic from issue body
        id: topic
        run: |
          BODY="${{ github.event.issue.body }}"
          BODY_LOWER=$(echo "$BODY" | tr '[:upper:]' '[:lower:]')
          if echo "$BODY_LOWER" | grep -q "javascript"; then
            echo "topic=javascript" >> $GITHUB_OUTPUT
          elif echo "$BODY_LOWER" | grep -q "css"; then
            echo "topic=css" >> $GITHUB_OUTPUT
          elif echo "$BODY_LOWER" | grep -q "react"; then
            echo "topic=react" >> $GITHUB_OUTPUT
          elif echo "$BODY_LOWER" | grep -q "jquery"; then
            echo "topic=jquery" >> $GITHUB_OUTPUT
          else
            echo "topic=general" >> $GITHUB_OUTPUT
          fi

      - name: Sanitize folder name from issue title
        id: folder
        run: |
          FOLDER=$(echo "${{ github.event.issue.title }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
          echo "folder=$FOLDER" >> $GITHUB_OUTPUT

      - name: Create README.md from issue
        run: |
          mkdir -p "errors/${{ steps.topic.outputs.topic }}/${{ steps.folder.outputs.folder }}"
          echo "# 🐞 ${GITHUB_EVENT_ISSUE_TITLE}" > "errors/${{ steps.topic.outputs.topic }}/${{ steps.folder.outputs.folder }}/README.md"
          echo "" >> "errors/${{ steps.topic.outputs.topic }}/${{ steps.folder.outputs.folder }}/README.md"
          echo "${{ github.event.issue.body }}" >> "errors/${{ steps.topic.outputs.topic }}/${{ steps.folder.outputs.folder }}/README.md"

      - name: Commit and push
        run: |
          git add .
          git commit -m "📚 Add error doc: ${{ github.event.issue.title }}" || echo "Nothing to commit"
          git push
