name: 📩 Store GitHub Issue as Markdown

on:
  issues:
    types: [opened]

jobs:
  store_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect topic from title + HTML-stripped body
        id: topic
        run: |
          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"

          BODY_STRIPPED=$(echo "$BODY" | sed 's/<[^>]*>//g')
          COMBINED=$(echo "$TITLE $BODY_STRIPPED" | tr '[:upper:]' '[:lower:]')

          TOPIC="general"

          if echo "$COMBINED" | grep -q "javascript"; then
            TOPIC="javascript"
          elif echo "$COMBINED" | grep -q "css"; then
            TOPIC="css"
          elif echo "$COMBINED" | grep -q "react"; then
            TOPIC="react"
          elif echo "$COMBINED" | grep -q "jquery"; then
            TOPIC="jquery"
          fi

          echo "Detected topic: $TOPIC"
          echo "topic=$TOPIC" >> $GITHUB_OUTPUT

      - name: Generate folder name from issue title
        id: folder
        run: |
          SAFE_NAME=$(echo "${{ github.event.issue.title }}" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g' | sed 's/^-*//;s/-*$//')
          echo "folder=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Print debug info
        run: |
          echo "Topic: ${{ steps.topic.outputs.topic }}"
          echo "Folder: ${{ steps.folder.outputs.folder }}"

      - name: Save issue as markdown file
        run: |
          mkdir -p "errors/${{ steps.topic.outputs.topic }}/${{ steps.folder.outputs.folder }}"

          FILE="errors/${{ steps.topic.outputs.topic }}/${{ steps.folder.outputs.folder }}/issue.md"

          {
            echo "# 🐞 ${{ github.event.issue.title }}"
            echo ""
            echo "Reported by: [@${{ github.event.issue.user.login }}](${{ github.event.issue.user.html_url }})"
            echo ""
            echo "${{ github.event.issue.body }}"
          } > "$FILE"

      - name: Commit and push markdown file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "📚 Add error doc: ${{ github.event.issue.title }}" || echo "No changes to commit"
          git push