name: Generate File Count Badge

on:
  push:
    branches: [main]  # Change if your default branch is not 'main'

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Count files
        run: |
          FILE_COUNT=$(find . -type f | wc -l)
          echo "Total files: $FILE_COUNT"
          echo "{\"schemaVersion\":1,\"label\":\"files\",\"message\":\"$FILE_COUNT\",\"color\":\"blue\"}" > filecount-badge.json

      - name: Commit badge
        env:
          TOKEN: ${{ secrets.OPENROCKETS_PAT }}
        run: |
          git config user.name "openrocketsofficial"
          git config user.email "motiontel@outlook.com"
          git remote set-url origin https://$TOKEN@github.com/${{ github.repository }}
          git add filecount-badge.json
          git commit -m "Update file count badge"
          git push
