# .github/workflows/files-badge.yml
name: Generate File Count Badge

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Count files
        run: |
          count=$(find . -type f | wc -l)
          echo "{\"schemaVersion\":1,\"label\":\"files\",\"message\":\"$count\",\"color\":\"blue\"}" > filecount-badge.json

      - name: Commit badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add filecount-badge.json
          git commit -m "Update file count badge"
          git push
